### ISSUE TITLE
Change Travis-CI and codecov from vsimko/biwavelet to tgouhier/biwavelet

### ISSUE THREAD

**Issue by vsimko** [tgouhier/biwavelet#2]
The links in `README.md` point to the status of `vsimko/biwavelet` repository.

You need to:
- Set up an account at https://travis-ci.org/ and turn on builds for `tgouhier/biwavelet`
- Set up an account at https://codecov.io
- Edit `README.md` as follows:

```
[![Build Status](https://travis-ci.org/tgouhier/biwavelet.svg)](https://travis-ci.org/tgouhier/biwavelet)
[![codecov.io](https://codecov.io/github/tgouhier/biwavelet/coverage.svg?branch=master)](https://codecov.io/github/tgouhier/biwavelet?branch=master)
```

**Comment by tgouhier** [comment]
Done; thanks for the instructions.
