### ISSUE TITLE
Align release note according to NEWS

### ISSUE THREAD

**Issue by vsimko** [tgouhier/biwavelet#32]
I have updated the `inst/NEWS.Rd` and realized that the [github releases (tags)](https://github.com/tgouhier/biwavelet/releases) do not have proper descriptions/comments.
@tgouhier Could you please update the descriptions according to the `NEWS.Rd` file ?

**Comment by tgouhier** [comment]
Will do.

**Comment by tgouhier** [comment]
All done.
