### ISSUE TITLE
New C++ warnings in arrayGeneric.h

### ISSUE THREAD

**Issue by tgouhier** [tgouhier/biwavelet#43]
Warnings generated when checking build:

./arrayGeneric.h:24:5: warning: control may reach end of non-void function [-Wreturn-type]
./arrayGeneric.h:36:5: warning: control may reach end of non-void function [-Wreturn-type]
./arrayGeneric.h:50:5: warning: control may reach end of non-void function [-Wreturn-type]

**Comment by vsimko** [comment]
`-Wreturn-type` now compiles without warnings

**Comment by tgouhier** [comment]
Great, thanks for providing a fix.

**Comment by vsimko** [comment]
btw, do you know how to configure rstudio so that `-Wreturn-type` is used when I'm compiling locally, but not used when compiling on Travis/CRAN ?

see https://travis-ci.org/vsimko/biwavelet/builds/128483555

```
checking compilation flags in Makevars ... WARNING
Non-portable flags in variable 'PKG_CPPFLAGS':
  -Wreturn-type 
```
