### ISSUE TITLE
tests for wt.bases.paul fail on 32bit platforms

### ISSUE THREAD

**Issue by vsimko** [tgouhier/biwavelet#46]
Here is the error:

> - checking tests ...
>   *\* running tests for arch 'i386' ... ERROR
>   Running the tests in 'tests/testthat.R' failed.
>   Last 13 lines of output:
>   # testthat results
>   
>   OK: 187 SKIPPED: 0 FAILED: 8
>   1. Failure: Optimized version of wt.bases.paul is equal to original
>      (@test-optimizations.R#24)
>   2. Failure: Optimized version of wt.bases.paul is equal to original
>      (@test-optimizations.R#30)
>   3. Failure: Optimized version of wt.bases.paul is equal to original
>      (@test-optimizations.R#24)
>   4. Failure: Optimized version of wt.bases.paul is equal to original
>      (@test-optimizations.R#30)
>   5. Failure: Optimized version of wt.bases.paul is equal to original
>      (@test-optimizations.R#24)
>   6. Failure: Optimized version of wt.bases.paul is equal to original
>      (@test-optimizations.R#30)
>   7. Failure: Optimized version of wt.bases.paul is equal to original
>      (@test-optimizations.R#24)
>   8. Failure: Optimized version of wt.bases.paul is equal to original
>      (@test-optimizations.R#30)
>   
>   Error: testthat unit tests failed
>   Execution halted

**Comment by vsimko** [comment]
@tgouhier please verify it works in your setup and then close the issue

**Comment by tgouhier** [comment]
Works for me but I'm on a 64bit machine.

**Comment by vsimko** [comment]
It is working in my vagrant/VirtualBox setup using 32bit debian:

```
vagrant init boxcutter/debian80-i386
```

**Comment by tgouhier** [comment]
Great, I pushed this version to CRAN.
