### ISSUE TITLE
Why is the .Random.seed needed?

### ISSUE THREAD

**Issue by vsimko** [tgouhier/biwavelet#55]
`.Random.seed`in file `R/biwavelet-internal.R`

**Comment by vsimko** [comment]
@tgouhier any ideas ?

**Comment by tgouhier** [comment]
I'm not sure. Perhaps to ensure reproducibility of the examples? I don't think it's critical so we can definitely lose the file.

**Comment by vsimko** [comment]
Regarding reproducibility, I think users should take care of this by themselves.
For example, at the top of a vignette file, I'm always using `set.seed(0)`

**Comment by tgouhier** [comment]
I agree. Shall we remove it then?
