### ISSUE TITLE
y-axis labels: better not to use digits in the format()

### ISSUE THREAD

**Issue by dankelley** [tgouhier/biwavelet#80]
I noticed that the labels on the y axis will be wrong if more than one digit after the decimal place is required, as in the test case given below. The problem is that the tick at period=0.25 is labelled as 0.2, because of the way `format` is called in `plot.biwavelet.R` line 233 from the most recent tarball in the CRAN archive.

```R
n <- 12 * 150 # e.g. many monthly climate indices, covering centuries
t <- 1800 + 1:n/12
x <- rnorm(n)
library("biwavelet")
wavelet <- wt(cbind(t, x))
plot(wavelet)
## Demonstrate that the period labelled 0.2 is actually 0.25
abline(h=log2(0.25))
```

**Comment by tgouhier** [comment]
Hi @dankelley,

Thanks for your patience with this bug. Anyway, the issue with the ytickmarks has been fixed in version 0.20.17 of biwavelet (https://github.com/tgouhier/biwavelet/tree/0.20.17).
