### ISSUE TITLE
installation error 0.20.17

### ISSUE THREAD

**Issue by Vasfocul** [tgouhier/biwavelet#81]
Hi, I can not install the package, it marks me the following error message¡¡¡

Installing package into ‘C:/Users/Martin}/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘biwavelet’
  These will not be installed

May you help me, please.

**Comment by tgouhier** [comment]
Hi,

You need to install Rtools in order to build biwavelet from source (https://cran.r-project.org/bin/windows/Rtools/).
