### ISSUE TITLE
dt argument in biwavelet::wt() is ignored

### ISSUE THREAD

**Issue by cdibble** [tgouhier/biwavelet#82]
Providing a value for `dt` does not appear to work. The value for dt that is returned is always 1. It appears that the function does not look for a user-input `dt`. It does come out of the `check.data()` routine with a `dt` of 1, though.

EG

```
        matrix.i <- as.matrix(data.frame(Ind = 1:1000, Y = sin(1:1000)))
	wav1 <- biwavelet::wt(matrix.i)
	str(wav1)
	wav2 <- biwavelet::wt(matrix.i, dt = 5)
	str(wav2)
```

Am I missing something about how this is supposed to work?

**Comment by r-scotti** [comment]
I understand that dt is listed as argument just to be able to specify s0 default value.
I would like to read thi detail in the documentation
