### ISSUE TITLE
The power matrix contains only zeros.

### ISSUE THREAD

**Issue by atusiniida** [tgouhier/biwavelet#89]
Dear colleagues, 

When I perform wavelet  transformation on the attached data, by following script,
the power matrix contains only zeros and I cannot plot data .
can you give me a help? 

D<-read.table("out.txt", header = TRUE)
wt.d=wt(D)
plot.biwavelet(wt.d)

[out.txt](https://github.com/tgouhier/biwavelet/files/9926788/out.txt)

**Comment by JAFERRARI** [comment]
[image: image.png]

https://publons.com/researcher/2717860/jose-a-ferrari/

.../\...(\_/).../\...
(((..\.[ °!° ]./..)))


Em qui., 3 de nov. de 2022 às 05:55, atusiniida ***@***.***>
escreveu:

**Comment by JAFERRARI** [comment]
[image: image.png]

Delete these rows!

https://publons.com/researcher/2717860/jose-a-ferrari/

.../\...(\_/).../\...
(((..\.[ °!° ]./..)))


Em qui., 3 de nov. de 2022 às 05:55, atusiniida ***@***.***>
escreveu:

**Comment by atusiniida** [comment]
Thanks, I should have checked my data in more details...
