### ISSUE TITLE
Question: Which variables are used in plot.biwavelet?

### ISSUE THREAD

**Issue by spencer-tassone** [tgouhier/biwavelet#90]
I am plotting the output of a wavelet transform, but I do not understand what is being plotted from the wavelet transform object. What variables are being used to create the wavelet transform plot?

Example Data
```
set.seed(321)
dat <- as.data.frame(matrix(nrow = 20222, ncol = 2))
colnames(dat)[1:2] <- c('datetime','value')
dat$datetime <- seq(as.POSIXct('2020-06-20 00:00', tz = "America/Jamaica", "%Y-%m-%d %H:%M"),
           by = 'hour',
           length.out = 20222)
x = seq(1,20222,2*pi/6.2832)
y1 = sin(x/1250) + 20
y2 = rnorm(n = 20222, mean = 0, sd = 0.3)
dat$value = y1 + y2
plot(dat)
```

Plotting the analysis output:

```
library(biwavelet)

# Convert time series to a continuous sequence to avoid error message associated with class POSIXct
dat$datetime <- seq(1,NROW(dat),1) 

test <- wt(dat) # test = wavelet transform object
View(test)

plot(test, # what is being plotted from the test object?
     plot.cb = F, plot.phase = F, plot.sig = F,
     alpha.coi = 0.7,
     col.coi = 'black',
     cex.axis = 1.5,
     cex.lab = 1.5)
```

It is unclear to me what is being plotted from inside of the ```test``` object.

**Comment by JAFERRARI** [comment]
Dear Spencer,
See the example below for the time series and the resulting wavelets.


library(biwavelet)
dat <- as.data.frame(matrix(nrow = 500, ncol = 2))

dat[1] <- seq(1,500)
dat[2] <- sin(dat[1])

plot(dat,type="b")
wvt <- wt(dat)
plot(wvt)

dat[2] <- sin(dat[1]*.5)
plot(dat,type="b")
wvt <- wt(dat)
plot(wvt)

dat[2] <- sin(dat[1]*.25)
plot(dat,type="b")
wvt <- wt(dat)
plot(wvt)

dat[2] <- sin(dat[1]*.125)
plot(dat,type="b")
wvt <- wt(dat)
plot(wvt)

dat[2] <- sin(dat[1]*.05)
plot(dat,type="b")
wvt <- wt(dat)
plot(wvt)



https://publons.com/researcher/2717860/jose-a-ferrari/

.../\...(\_/).../\...
(((..\.[ °!° ]./..)))


Em seg., 30 de jan. de 2023 às 12:24, spencer-tassone <
***@***.***> escreveu:

**Comment by spencer-tassone** [comment]
@JAFERRARI Yes, I understand ***how*** to plot ```wt``` objects using ```plot()``` (*please see the example I provided in the original post*). I also understand what the output of ```plot(wvt)``` is. 

What I do not understand: what is ```plot()``` pulling from inside of ```wvt``` to create the figure? You can see what is inside of ```wvt``` using ```View(wvt)```, what is it in there that is being used to create the period-time figure?

**Comment by JAFERRARI** [comment]
The plot uses a matrix containing the wavelet transform.

see "Wave"  in biwavelet documentation.

https://cran.r-project.org/web/packages/biwavelet/biwavelet.pdf
